apiVersion: v1
kind: Service
metadata:
  name: ric-service
spec:
  selector:
    app: ric-platform
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ric-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ric-platform
  template:
    metadata:
      labels:
        app: ric-platform
    spec:
      containers:
      - name: ric
        image: oran-lab:v1
        imagePullPolicy: IfNotPresent
        command: ["python", "-u", "ric_mestre.py"]
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xapp-traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xapp-functional
  template:
    metadata:
      labels:
        app: xapp-functional
    spec:
      containers:
      - name: xapp
        image: oran-lab:v1
        imagePullPolicy: IfNotPresent
        command: ["python", "-u", "xapp_mock.py"]
        env:
        - name: RIC_HOST
          value: "ric-service"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapp-energy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rapp
  template:
    metadata:
      labels:
        app: rapp
    spec:
      containers:
      - name: rapp
        image: oran-lab:v1
        imagePullPolicy: IfNotPresent
        command: ["python", "-u", "rapp_mock.py"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bench-worker
  template:
    metadata:
      labels:
        app: bench-worker
    spec:
      containers:
      - name: worker
        image: oran-lab:v1
        imagePullPolicy: IfNotPresent
        command: ["python", "-u", "app_worker.py"]
        env:
        - name: RIC_HOST
          value: "ric-service"
        resources:
          limits:
            cpu: "50m"
            memory: "50Mi"